config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'

  post '/users/edit', to: 'users#update'

  resources :services

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :services
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  belongs_to :service
  enum pricing_type: [:basic, :standard, :premium]
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :pricings
  has_many_attached :photos
  has_rich_text :description

  accepts_nested_attributes_for :pricings

  validates :title, presence: { message: 'cannot be blank' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar
  has_many :services        

  validates :full_name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

     if user
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider


      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
    end

    def after_sign_in_path_for(resource)
        dashboard_path
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    protected
    def update_resource(resource, params)
        resource.update_without_password(params)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :set_service, except: [:new, :create]
  before_action :is_authorised, only: [:edit, :update]
  before_action :set_step, only: [:update, :edit]

  def new
    @service = current_user.services.build
    @categories = Category.all
  end

  def create
    @service = current_user.services.build(service_params)

    if @service.save
      @service.pricings.create(Pricing.pricing_types.values.map{ |x| {pricing_type: x} })
      redirect_to edit_service_path(@service), notice: "Save..."
    else
      redirect_to request.referrer, flash: { error: @service.errors.full_messages }
    end
  end

  def edit
    @categories = Category.all
  end

  def update
      if @step == 2
    service_params[:pricings_attributes].each do |index, pricing|
      if @service.has_single_pricing && pricing[:pricing_type] != Pricing.pricing_types.key(0)
        next;
      else
        if pricing[:title].blank? || pricing[:description].blank? || pricing[:delivery_time].blank? || pricing[:price].blank?
          return redirect_to request.referrer, flash: {error: "Invalid pricing"}
        end
      end
    end
  end

  if @step == 3 && service_params[:description].blank?
    return redirect_to request.referrer, flash: {error: "Description cannot be blank"}
  end

  if @step == 4 && @service.photos.blank?
    return redirect_to request.referrer, flash: {error: "You don't have any photos"}
  end

  if @step == 5
    @service.pricings.each do |pricing|
      if @service.has_single_pricing && !pricing.basic?
        next;
      else
        if pricing[:title].blank? || pricing[:description].blank? || pricing[:delivery_time].blank? || pricing[:price].blank?
          return redirect_to edit_service_path(@service, step: 2), flash: {error: "Invalid pricing"}
        end
      end
    end

    if @service.description.blank?
      return redirect_to edit_service_path(@service, step: 3), flash: {error: "Description cannot be blank"}
    elsif @service.photos.blank?
      return redirect_to edit_service_path(@service, step: 4), flash: {error: "You don't have any photos"}
    end
  end

  if @service.update(service_params)
    flash[:notice] = "Saved..."
  else
    return redirect_to request.referrer, flash: {error: @service.errors.full_messages}
  end

  if @step < 5
    redirect_to edit_service_path(@service, step: @step + 1)
  else
    redirect_to dashboard_path
  end

end

  end

  def show
  end

  private

  def set_step
    @step = params[:step].to_i > 0 ? params[:step].to_i : 1
    if @step > 5
      @step = 5
    end
  end

  def set_service
    @service = Service.find(params[:id])
  end

  def is_authorised
    redirect_to root_path, alert: "You do not have permission" unless current_user.id == @service.user_id
  end

  def service_params
    params.require(:service).permit(:title, :video, :description, :active, :category_id, :has_single_pricing, 
                                pricings_attributes: [:id, :title, :description, :delivery_time, :price, :pricing_type])
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update_attributes(current_user_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot update..."
    end
    redirect_to dashboard_path
  end

  private
  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_url(user)
        if user.avatar.attached?
            url_for(user.avatar)
        elsif user.image?
            user.image
        else
            ActionController::Base.helpers.asset_path('icon_default_avatar.png')
        end
    end

    def service_cover(service)
        if service.photos.attached?
            url_for(gig.photos[0])
        else
            ActionController::Base.helpers.asset_path('icon_default_image.png')
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>fFreelance</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">


  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render  "shared/navbar" %>
  <%= render "shared/notification" %>
  <%= yield %>
</body>

</html>

app/views/pages/home.html.erb
<h1>Welcome to the home page!</h1>

app/views/services/_step1.html.erb
<div class="step-content <%= 'is-active' if @step == 1 %>">
      <div class="field">
        <label class="label">Service Title</label>
        <%= f.text_area :title, autocomplete: "title", class: "textarea" %>
      </div>
      <div class="field">
        <label class="label">Category</label>
        <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: @service.category_id)) %>
      </div>
      <div class="field">
        <label class="checkbox">
            <%= f.check_box :has_single_pricing, class: "checkbox", onchange: "this.form.submit();" %> Has Single Price
        </label>
      </div>
</div>

app/views/services/_step2.html.erb
<div class="step-content <%= 'is-active' if @step == 2 %>">
    <div class="field">
        <div class="control">
            <div class="columns has-text-centered">

                <%= f.fields_for :pricings, @service.pricings.order(:pricing_type) do |p| %>
                    <div class="column <%= 'is-4 is-offset-4' if @service.has_single_pricing && p.object.basic? %>
                                      <%= 'is-hidden' if @service.has_single_pricing && !p.object.basic? %> ">
                        <label for="" class="label"><%= p.object.pricing_type.capitalize %></label>
                        <%= p.hidden_field :pricing_type %>

                        <div class="control">
                            <%= p.text_field :title, placeholder: "Title", class: "input is-radiusless" %>
                        </div>

                        <div class="control">
                            <%= p.text_area :description, placeholder: "Description", class: "textarea is-radiusless" %>
                        </div>

                        <div class="control has-icons-right">
                            <%= p.number_field :delivery_time, placeholder: "Delivery Time", class: "input is-radiusless", default: 1 %>
                            <span class="icon is-small is-right">days</span>
                        </div>

                        <div class="control has-icons-right">
                            <%= p.number_field :price, placeholder: "Price", class: "input is-radiusless", default: 1 %>
                            <span class="icon is-small is-right">$</span>
                        </div>

                    </div>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/services/_step3.html.erb
<div class="step-content <%= 'is-active' if @step == 3 %>">
    <div class="field">
        <label for="" class="label">Description</label>
        <%= f.rich_text_area :description, rows: 50, cols: 50 %>
    </div>
</div>

app/views/services/_step4.html.erb
<div class="step-content <%= 'is-active' if @step == 4 %>">
    <div class="field">
        <label for="" class="label">Youtube Code</label>
        <%= f.text_field :video, autocomplete: "video url", class: "input" %>
    </div>

    <div class="field">
        <label for="" class="label">Build your Services Gallery</label>
        <div class="control">
            <div class="m-b-20">
                <div class="dropzone" id="myDropzone" action="/services/<%= @service.id %>/upload_photo"></div>
            </div>

            <div class="columns is-multiline" style: width: 100%%>
                <% @service.photos.each do |photo| %>
                    <div class="column is-one-fifth">
                        <div class="card is-image">
                            <div class="card-image">
                                <%= link_to 'Remove', delete_photo_service_url(photo_id: photo.id, id: @service.id, step: @step), 
                                        method: :delete,
                                        data: { confirm: "Are you sure?" },
                                        class: "delete delete-file is-pulled-right",
                                        style: "z-index: 100"  %>

                                <figure class="image is-4by3">
                                    <%= image_tag url_for(photo) %>
                                </figure>
                            </div>
                        </div>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    Dropzone.options.myDropzone = {
        paramName: "file",
        maxFilesize: 2,
        acceptedFiles: "image/*",
        init: function() {
            this.on('complete', function (file) {
                location.reload();
            })
        }
    }
</script>

app/views/services/_step5.html.erb
<div class="step-content has-text-centered <%= 'is-active' if @step == 5 %>">
    <div>
        <%= hidden_field_tag 'active', 'true' if @step == 5 %>
        <strong class="is-size-2">Almost there...</strong>
        <p>Let's publish your Service and get some buyers rolling in.</p>
    </div>
</div>

<div class="field is-grouped is-grouped-centered m-t-25">
    <p class="control <%= 'is-hidden' if @step <= 1 %>">
        <%= link_to 'Back', edit_service_path(@service, step: @step - 1), class: "button is-danger" %>
    </p>

    <p class="control">
        <% if @step != 5 %>
            <%= f.submit 'Save & Continue', class: "button is-link" %>
        <% else %>
            <%= link_to 'Publish', service_path(@service.id, service: {active: true}, step: @step), 
                        method: :put, 
                        data: {confirm: "Do you want to publish this service?"},
                        class: "button is-link" %>
        <% end %>
    </p>
</div>

app/views/services/edit.html.erb
<section class="section">
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item <%= 'is-active is-success' if @step == 1 %><%= 'is-completed is-warning' if @step > 1 %>">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active is-success' if @step == 2 %><%= 'is-completed is-warning' if @step > 2 %>">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Pricing</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active is-success' if @step == 3 %><%= 'is-completed is-warning' if @step > 3 %>">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active is-success' if @step == 4 %><%= 'is-completed is-warning' if @step > 4 %>">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active is-success' if @step == 5 %><%= 'is-completed is-warning' if @step > 5 %>">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW SERVICE HERE-->
      <%= form_for @service, html: {class: "steps-content m-l-100 m-r-100"} do |f| %>
        <%= hidden_field_tag 'step', @step %>
        
        <%= render 'step1', f: f %>
        <%= render 'step2', f: f %>
        <%= render 'step3', f: f %>
        <%= render 'step4', f: f %>
        <%= render 'step5', f: f %>

      <% end %>
    </div>
  </div>
</section>

app/views/services/new.html.erb
<section class="section">
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item is-active">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Pricing</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW GIG HERE-->
      <%= form_for @service, html: {class: "steps-content m-l-100 m-r-100"} do |f| %>
        <div class="field">
            <label class="label">Service Title</label>
            <%= f.text_area :title, autocomplete: "title", class: "textarea" %>
        </div>
        <div class="field">
            <label class="label">Category</label>
            <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] })) %>
        </div>
        <div class="field is-grouped is-grouped-centered m-t-25">
            <a href="" data-nav="previous" class="button is-link">Cancel</a>
            <%= f.submit "Save & Continue", class: "button is-light" %>
        </div>

      <% end %>
    </div>
  </div>
</section>

app/views/services/show.html.erb
<h1>Services#show</h1>
<p>Find me in app/views/services/show.html.erb</p>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          new Noty ({
              type: '<%= type %>',
              layout: 'topRight',
              timeout: '3000',
              theme: 'sunset',
              text: '<%= value %>'
          }).show();
        <% end %>
    </script>
<% end %>

app/views/users/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                                <figure class="image is-128x128">
                                    <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                                </figure>
                            </div>
                            
                            <div class="card-content">

                       <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= current_user.full_name %></p>
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post do |f| %>
                                        <div class="file">
                                            <label class="button is-link is-outlined is-fullwidth">
                                                <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit();" %>
                                                <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp; Upload Avatar
                                            </label>
                                        </div>
                                    <% end %>
                                </div>
                                <hr class="h-10">
                                
                                <!-- Member -->
                                <article class="media">
                                    <div class="media-content">Member since</div>
                                    <div class="media-right">
                                        <strong><%= current_user.created_at.strftime('%b %Y') %></strong>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- From -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">From</div>
                                        <div class="media-right">
                                            <strong><%= current_user.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-from', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-danger" aria-controls="user-from">Cancel</a>
                                            <%= f.submit "Save", class: "button is-light" %>
                                        <% end %>
                                    </div>

                                </article>                                
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Online Status</div>
                                        <div class="media-right">
                                            <strong><% if current_user.status %> Online <% else %> Offline <% end %></strong> <i class="toggle far fa-edit" aria-controls="user-status"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-status', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.select(:status, options_for_select([["Online", true], ["Offline", false]]), {}, {class: "select is-fullwidth"}) %>
                                            </div>
                                            <a class="toggle button is-danger" aria-controls="user-status">Cancel</a>
                                            <%= f.submit "Save", class: "button is-light" %>
                                        <% end %>
                                    </div>
                                </article>

                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>About Yourself</strong>
                                                <br>
                                                <%= current_user.about %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-about"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-about', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_area :about, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-danger" aria-controls="user-about">Cancel</a>
                                            <%= f.submit "Save", class: "button is-light" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Language -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>Language</strong>
                                                <br>
                                                <%= current_user.language %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-language"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-language', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :language, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-danger" aria-controls="user-language">Cancel</a>
                                            <%= f.submit "Save", class: "button is-light" %>
                                        <% end %>
                                    </div>

                                </article>
                                <hr class="h-10">
                                
                                <!-- Linked Account -->
                                <article class="media">
                                    <div class="content">
                                        <p>
                                            <strong>Linked Account</strong><br/>
                                            <% if current_user.provider %>
                                                <span class="has-text-success">Facebook verified</span>
                                            <% else %>
                                                <%= link_to 'Connect to Facebook', user_facebook_omniauth_authorize_path, class: "has-text-danger" %>
                                            <% end %>
                                        </p>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Create New Gig -->
                    <div class="column is-one-third has-text-centered"></div>

                    <!-- Sample Gig -->
                    <div class="column is-one-third has-text-centered"></div>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>